apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: 314937863587.dkr.ecr.us-east-1.amazonaws.com/my-cloud-native-repo:latest
        ports:
        - containerPort: 5000
